let newPostTwo = [
  {
    category: "Shopping",
    imagesrc:
      "https://drive.google.com/thumbnail?id=1u15qkLx0UJ9ZWFO5Ymsjqw-rqEtZujCt&sz=s4000",
    postNumber: 10,
    title: "Metro Gaisano Bais City - First Mall in the city",
    desc: "The Metro in Bais City finally opens its doors on August 15, 2025. Making it the first mall in the city and the first Metro in Negros Oriental",
    datePublished: "25 Aug 2025",
    comments: "5",
    link: "./metro-gaisano-bais-city",
    location: "Bais City",
    author: "Ren Calago",
  },
  {
    category: "Travel",
    imagesrc:
      "https://drive.google.com/thumbnail?id=1XTlpJQlYZzI8TL1u077lOkj92Tj6jL4y&sz=s4000",
    postNumber: 10,
    title: "The Venice Grand Canal in McKinley Hill, Taguig",
    desc: "The place for fine dining, leisure and pure relaxation. Meet some friends, take a boat ride through the canal or stroll around.",
    datePublished: "14 Sep 2024",
    comments: "",
    link: "./venice-grand-canal-mckinley-hill",
    location: "Baguio City",
    author: "Ren Calago",
  },
  {
    category: "Travel",
    imagesrc:
      "https://drive.google.com/thumbnail?id=1wYVQLCG2rfVX6D9L1WTkFz6lQLQ3Vire&sz=s4000",
    postNumber: 9,
    title: "Travel to Baguio City - Places to Visit",
    desc: "Without a doubt, Baguio City is one of the top tourist destination in the Philippines. Thanks to its cool temperature, and numerous fun things to-do!",
    datePublished: "12 Sep 2024",
    comments: "",
    link: "./travel-to-baguio-city-places-to-visit",
    location: "Baguio City",
    author: "Ren Calago",
  },
  {
    category: "Travel",
    imagesrc:
      "https://drive.google.com/thumbnail?id=1b3L0Tqpxi2sOuY_C-RFFthNZePHshdSR&sz=s4000",
    postNumber: 8,
    title: "Travel to Dumaguete City: Places to Visit",
    desc: "Dumaguete is known its unique tourist spots like Pulangbato falls, forest camp in Valencia and the twin lake balinsasayao",
    datePublished: "26 Mar 2023",
    comments: "",
    link: "./travel-to-dumaguete-places-to-visit",
    location: "Dumaguete City",
    author: "Ren Calago",
  },
  {
    category: "Travel",
    imagesrc:
      "https://drive.google.com/thumbnail?id=14kJ3ou0ndreCtKhk8jvGo0dZpZOGjlnZ&sz=s4000",
    postNumber: 7,
    title: "First Time at Cebu Ocean Park",
    desc: "The Cebu Ocean Park is a must-visit in Cebu City. This unique experience is well-suited for people who wants to enjoy discovering our marine biodiversity.",
    datePublished: "8 Mar 2023",
    comments: "",
    link: "./cebu-ocean-park",
    location: "Cebu City",
    author: "Ren Calago",
  },
  {
    category: "Cafes & Restaurant",
    imagesrc:
      "https://drive.google.com/thumbnail?id=1PnHpobsmOVrqYdQLSwYYsW1LiHas6Tai&sz=s4000",
    postNumber: 6,
    title: "Alimyon Kapehan San Jose",
    desc: "Alimyon Kapehan is a unique filipino-styled restaurant that offers not just tasty food but good view of the mountain.",
    datePublished: "25 Feb 2023",
    comments: "",
    link: "./alimyon-kapehan-san-jose",
    location: "San Jose, Negros Oriental",
    author: "Ren Calago",
  },
  {
    category: "Nature",
    imagesrc:
      "https://drive.google.com/thumbnail?id=1CdEFIWR21dI3X34Kkv0HpPrQYY4-V6TI&sz=s4000",
    postNumber: 5,
    title: "A Day In Cebu Safari and Adventure Park",
    desc: "Spend a day surrounded by nature, explore the unfamiliar and see the wilds up close. You'll go back home in awe to your new spot for exploration. Cebu Safari and Adventure Park is a must-visit family friend park.",
    datePublished: "18 Feb 2023",
    comments: "",
    link: "./cebu-safari-adventure",
    location: "Carmen, Cebu",
    author: "Ren Calago",
  },
  {
    category: "Beach Resort",
    imagesrc:
      "https://drive.google.com/thumbnail?id=10nme7clU1_5CXZ7NG6MpgM2whNunI_RX&sz=s4000",
    postNumber: 4,
    title: "Lalimar Beach Resort - Infinite Relaxation ",
    desc: "How about taking a dip on its infinite pool while enjoying the sunset view of the horizon? Or just sit in the Cabana with refreshments you craved for.",
    datePublished: "14 Feb 2023",
    comments: "14",
    link: "./lalimar-beach-resort-la-libertad",
    location: "La Libertad",
    author: "Ren Calago",
  },
  {
    category: "Cafes & Restaurant",
    imagesrc:
      "https://drive.google.com/thumbnail?id=13grQ-pFx34CXhk0NfitlPV0g7n361VyB&sz=s4000",
    postNumber: 3,
    title: "Victoria's Mountainview Resort Tanjay City",
    desc: "Dine in  while giving your eyes a feast of an amazing view. Victorias Mountainview is simply the best in the city. You will be treated with awesome scenery going to this place.",
    datePublished: "13 Feb 2023",
    comments: "",
    link: "./victorias-mountain-view-tanjay-city",
    location: "Tanjay City",
    author: "Ren Calago",
  },
  {
    category: "Cafes & Restaurant",
    imagesrc:
      "https://drive.google.com/thumbnail?id=1n8e8tr-5NeiW7jx7K0YMU7SbmliN2OzI&sz=s4000",
    postNumber: 2,
    title: "Sakada, a cafe on the Mountain",
    desc: "Order your coffee at this mountain-top restaurant in Pamplona, Negros Oriental. It offers vibrant and cozy atmosphere with views like you've never seen before. ",
    datePublished: "11 Feb 2023",
    comments: "2",
    link: "./sakada-cafe-and-farm-pamplona",
    location: "Pamplona",
    author: "Ren Calago",
  },
  {
    category: "Travel",
    imagesrc:
      "https://drive.google.com/thumbnail?id=16fR0SpWq1j_5y6cK29xpxYX7Mhg7x6MQ&sz=s4000",
    postNumber: 1,
    title: "Tops Cebu Lookout - Busay, Cebu City",
    desc: "See the skyline of Cebu City from up the hill of Busay Cebu City. It has the best view of metropolitan Cebu. I think a month after we visited here, this spot in busay is closed for visitors.",
    datePublished: "10 Feb 2023",
    comments: "61",
    link: "./tops-cebu-look-out",
    location: "cebu",
    author: "Ren Calago",
  },
];

export { newPostTwo };
